// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: func.proto

package _func

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FuncService service

func NewFuncServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FuncService service

type FuncService interface {
	FetchControlUnitList(ctx context.Context, in *FetchListRequest, opts ...client.CallOption) (*FetchListResponse, error)
	AddControlUnit(ctx context.Context, in *AddControlUnitRequest, opts ...client.CallOption) (*Response, error)
	GetSubFuncId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeleteControlUnit(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type funcService struct {
	c    client.Client
	name string
}

func NewFuncService(name string, c client.Client) FuncService {
	return &funcService{
		c:    c,
		name: name,
	}
}

func (c *funcService) FetchControlUnitList(ctx context.Context, in *FetchListRequest, opts ...client.CallOption) (*FetchListResponse, error) {
	req := c.c.NewRequest(c.name, "FuncService.FetchControlUnitList", in)
	out := new(FetchListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *funcService) AddControlUnit(ctx context.Context, in *AddControlUnitRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FuncService.AddControlUnit", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *funcService) GetSubFuncId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FuncService.GetSubFuncId", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *funcService) DeleteControlUnit(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FuncService.DeleteControlUnit", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FuncService service

type FuncServiceHandler interface {
	FetchControlUnitList(context.Context, *FetchListRequest, *FetchListResponse) error
	AddControlUnit(context.Context, *AddControlUnitRequest, *Response) error
	GetSubFuncId(context.Context, *Request, *Response) error
	DeleteControlUnit(context.Context, *Request, *Response) error
}

func RegisterFuncServiceHandler(s server.Server, hdlr FuncServiceHandler, opts ...server.HandlerOption) error {
	type funcService interface {
		FetchControlUnitList(ctx context.Context, in *FetchListRequest, out *FetchListResponse) error
		AddControlUnit(ctx context.Context, in *AddControlUnitRequest, out *Response) error
		GetSubFuncId(ctx context.Context, in *Request, out *Response) error
		DeleteControlUnit(ctx context.Context, in *Request, out *Response) error
	}
	type FuncService struct {
		funcService
	}
	h := &funcServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FuncService{h}, opts...))
}

type funcServiceHandler struct {
	FuncServiceHandler
}

func (h *funcServiceHandler) FetchControlUnitList(ctx context.Context, in *FetchListRequest, out *FetchListResponse) error {
	return h.FuncServiceHandler.FetchControlUnitList(ctx, in, out)
}

func (h *funcServiceHandler) AddControlUnit(ctx context.Context, in *AddControlUnitRequest, out *Response) error {
	return h.FuncServiceHandler.AddControlUnit(ctx, in, out)
}

func (h *funcServiceHandler) GetSubFuncId(ctx context.Context, in *Request, out *Response) error {
	return h.FuncServiceHandler.GetSubFuncId(ctx, in, out)
}

func (h *funcServiceHandler) DeleteControlUnit(ctx context.Context, in *Request, out *Response) error {
	return h.FuncServiceHandler.DeleteControlUnit(ctx, in, out)
}
