// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: func.proto

package _func

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FuncService service

func NewFuncServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FuncService service

type FuncService interface {
}

type funcService struct {
	c    client.Client
	name string
}

func NewFuncService(name string, c client.Client) FuncService {
	return &funcService{
		c:    c,
		name: name,
	}
}

// Server API for FuncService service

type FuncServiceHandler interface {
}

func RegisterFuncServiceHandler(s server.Server, hdlr FuncServiceHandler, opts ...server.HandlerOption) error {
	type funcService interface {
	}
	type FuncService struct {
		funcService
	}
	h := &funcServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FuncService{h}, opts...))
}

type funcServiceHandler struct {
	FuncServiceHandler
}
