// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: role.proto

package role

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RoleService service

func NewRoleServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RoleService service

type RoleService interface {
	GetSubSysInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*SubSysInfoResponse, error)
}

type roleService struct {
	c    client.Client
	name string
}

func NewRoleService(name string, c client.Client) RoleService {
	return &roleService{
		c:    c,
		name: name,
	}
}

func (c *roleService) GetSubSysInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*SubSysInfoResponse, error) {
	req := c.c.NewRequest(c.name, "RoleService.GetSubSysInfo", in)
	out := new(SubSysInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoleService service

type RoleServiceHandler interface {
	GetSubSysInfo(context.Context, *Request, *SubSysInfoResponse) error
}

func RegisterRoleServiceHandler(s server.Server, hdlr RoleServiceHandler, opts ...server.HandlerOption) error {
	type roleService interface {
		GetSubSysInfo(ctx context.Context, in *Request, out *SubSysInfoResponse) error
	}
	type RoleService struct {
		roleService
	}
	h := &roleServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RoleService{h}, opts...))
}

type roleServiceHandler struct {
	RoleServiceHandler
}

func (h *roleServiceHandler) GetSubSysInfo(ctx context.Context, in *Request, out *SubSysInfoResponse) error {
	return h.RoleServiceHandler.GetSubSysInfo(ctx, in, out)
}
