// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

package role

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	EmployeeId           string   `protobuf:"bytes,1,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	RoleId               string   `protobuf:"bytes,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *Request) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SubSysInfoRequest struct {
	Simple               bool     `protobuf:"varint,1,opt,name=simple,proto3" json:"simple,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSysInfoRequest) Reset()         { *m = SubSysInfoRequest{} }
func (m *SubSysInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SubSysInfoRequest) ProtoMessage()    {}
func (*SubSysInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{2}
}

func (m *SubSysInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSysInfoRequest.Unmarshal(m, b)
}
func (m *SubSysInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSysInfoRequest.Marshal(b, m, deterministic)
}
func (m *SubSysInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSysInfoRequest.Merge(m, src)
}
func (m *SubSysInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SubSysInfoRequest.Size(m)
}
func (m *SubSysInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSysInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubSysInfoRequest proto.InternalMessageInfo

func (m *SubSysInfoRequest) GetSimple() bool {
	if m != nil {
		return m.Simple
	}
	return false
}

type SubSysInfoResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	SubSysInfo           string   `protobuf:"bytes,2,opt,name=subSysInfo,proto3" json:"subSysInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSysInfoResponse) Reset()         { *m = SubSysInfoResponse{} }
func (m *SubSysInfoResponse) String() string { return proto.CompactTextString(m) }
func (*SubSysInfoResponse) ProtoMessage()    {}
func (*SubSysInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{3}
}

func (m *SubSysInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSysInfoResponse.Unmarshal(m, b)
}
func (m *SubSysInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSysInfoResponse.Marshal(b, m, deterministic)
}
func (m *SubSysInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSysInfoResponse.Merge(m, src)
}
func (m *SubSysInfoResponse) XXX_Size() int {
	return xxx_messageInfo_SubSysInfoResponse.Size(m)
}
func (m *SubSysInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSysInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubSysInfoResponse proto.InternalMessageInfo

func (m *SubSysInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SubSysInfoResponse) GetSubSysInfo() string {
	if m != nil {
		return m.SubSysInfo
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "role.Request")
	proto.RegisterType((*Response)(nil), "role.Response")
	proto.RegisterType((*SubSysInfoRequest)(nil), "role.SubSysInfoRequest")
	proto.RegisterType((*SubSysInfoResponse)(nil), "role.SubSysInfoResponse")
}

func init() { proto.RegisterFile("role.proto", fileDescriptor_48a3ff9f7c9032f8) }

var fileDescriptor_48a3ff9f7c9032f8 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xca, 0xcf, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x1c, 0xb9, 0xd8, 0x83, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xe4, 0xb8, 0xb8, 0x52, 0x73, 0x0b, 0x72, 0xf2, 0x2b, 0x53,
	0x53, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x84, 0xc4, 0xb8, 0xd8,
	0x40, 0x5a, 0x3c, 0x53, 0x24, 0x98, 0xc0, 0x72, 0x50, 0x9e, 0x92, 0x0c, 0x17, 0x47, 0x50, 0x6a,
	0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0x3a, 0x54, 0x33, 0x88,
	0xa9, 0xa4, 0xcd, 0x25, 0x18, 0x5c, 0x9a, 0x14, 0x5c, 0x59, 0xec, 0x99, 0x97, 0x96, 0x0f, 0xb3,
	0x4a, 0x8c, 0x8b, 0xad, 0x38, 0x33, 0xb7, 0x20, 0x27, 0x15, 0xac, 0x92, 0x23, 0x08, 0xca, 0x53,
	0x72, 0xe3, 0x12, 0x42, 0x56, 0x8c, 0xcb, 0x50, 0x90, 0x53, 0x8b, 0xe1, 0xea, 0xa0, 0xce, 0x41,
	0x12, 0x31, 0x0a, 0xe6, 0xe2, 0x06, 0x39, 0x2e, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8,
	0x85, 0x8b, 0xd7, 0x3d, 0xb5, 0x04, 0x61, 0xb2, 0x90, 0xb8, 0x1e, 0x38, 0x20, 0x30, 0x1c, 0x26,
	0x25, 0x81, 0x29, 0x01, 0x71, 0x84, 0x12, 0x83, 0x13, 0x47, 0x14, 0x9b, 0x9e, 0x35, 0x48, 0x3a,
	0x89, 0x0d, 0x1c, 0x82, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x85, 0x6a, 0xc8, 0x9e, 0x4f,
	0x01, 0x00, 0x00,
}
