// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

package role

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	EmployeeId           string   `protobuf:"bytes,1,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	RoleId               string   `protobuf:"bytes,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *Request) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SubSysInfoRequest struct {
	Simple               int32    `protobuf:"varint,1,opt,name=simple,proto3" json:"simple,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSysInfoRequest) Reset()         { *m = SubSysInfoRequest{} }
func (m *SubSysInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SubSysInfoRequest) ProtoMessage()    {}
func (*SubSysInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{2}
}

func (m *SubSysInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSysInfoRequest.Unmarshal(m, b)
}
func (m *SubSysInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSysInfoRequest.Marshal(b, m, deterministic)
}
func (m *SubSysInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSysInfoRequest.Merge(m, src)
}
func (m *SubSysInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SubSysInfoRequest.Size(m)
}
func (m *SubSysInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSysInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubSysInfoRequest proto.InternalMessageInfo

func (m *SubSysInfoRequest) GetSimple() int32 {
	if m != nil {
		return m.Simple
	}
	return 0
}

type SubSysInfoResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	SubSysInfo           string   `protobuf:"bytes,2,opt,name=subSysInfo,proto3" json:"subSysInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSysInfoResponse) Reset()         { *m = SubSysInfoResponse{} }
func (m *SubSysInfoResponse) String() string { return proto.CompactTextString(m) }
func (*SubSysInfoResponse) ProtoMessage()    {}
func (*SubSysInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{3}
}

func (m *SubSysInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSysInfoResponse.Unmarshal(m, b)
}
func (m *SubSysInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSysInfoResponse.Marshal(b, m, deterministic)
}
func (m *SubSysInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSysInfoResponse.Merge(m, src)
}
func (m *SubSysInfoResponse) XXX_Size() int {
	return xxx_messageInfo_SubSysInfoResponse.Size(m)
}
func (m *SubSysInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSysInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubSysInfoResponse proto.InternalMessageInfo

func (m *SubSysInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SubSysInfoResponse) GetSubSysInfo() string {
	if m != nil {
		return m.SubSysInfo
	}
	return ""
}

type RoleListRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AdminId              string   `protobuf:"bytes,2,opt,name=adminId,proto3" json:"adminId,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleListRequest) Reset()         { *m = RoleListRequest{} }
func (m *RoleListRequest) String() string { return proto.CompactTextString(m) }
func (*RoleListRequest) ProtoMessage()    {}
func (*RoleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{4}
}

func (m *RoleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListRequest.Unmarshal(m, b)
}
func (m *RoleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListRequest.Marshal(b, m, deterministic)
}
func (m *RoleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListRequest.Merge(m, src)
}
func (m *RoleListRequest) XXX_Size() int {
	return xxx_messageInfo_RoleListRequest.Size(m)
}
func (m *RoleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListRequest proto.InternalMessageInfo

func (m *RoleListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleListRequest) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

func (m *RoleListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RoleListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RoleListResponse struct {
	RoleInfoList         []*RoleInfo `protobuf:"bytes,1,rep,name=roleInfoList,proto3" json:"roleInfoList,omitempty"`
	Total                int32       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoleListResponse) Reset()         { *m = RoleListResponse{} }
func (m *RoleListResponse) String() string { return proto.CompactTextString(m) }
func (*RoleListResponse) ProtoMessage()    {}
func (*RoleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{5}
}

func (m *RoleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListResponse.Unmarshal(m, b)
}
func (m *RoleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListResponse.Marshal(b, m, deterministic)
}
func (m *RoleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListResponse.Merge(m, src)
}
func (m *RoleListResponse) XXX_Size() int {
	return xxx_messageInfo_RoleListResponse.Size(m)
}
func (m *RoleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListResponse proto.InternalMessageInfo

func (m *RoleListResponse) GetRoleInfoList() []*RoleInfo {
	if m != nil {
		return m.RoleInfoList
	}
	return nil
}

func (m *RoleListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type NewRoleRequest struct {
	RoleInfo             *RoleInfo `protobuf:"bytes,1,opt,name=roleInfo,proto3" json:"roleInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NewRoleRequest) Reset()         { *m = NewRoleRequest{} }
func (m *NewRoleRequest) String() string { return proto.CompactTextString(m) }
func (*NewRoleRequest) ProtoMessage()    {}
func (*NewRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{6}
}

func (m *NewRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRoleRequest.Unmarshal(m, b)
}
func (m *NewRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRoleRequest.Marshal(b, m, deterministic)
}
func (m *NewRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRoleRequest.Merge(m, src)
}
func (m *NewRoleRequest) XXX_Size() int {
	return xxx_messageInfo_NewRoleRequest.Size(m)
}
func (m *NewRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewRoleRequest proto.InternalMessageInfo

func (m *NewRoleRequest) GetRoleInfo() *RoleInfo {
	if m != nil {
		return m.RoleInfo
	}
	return nil
}

type RoleInfo struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AdminId              string   `protobuf:"bytes,4,opt,name=adminId,proto3" json:"adminId,omitempty"`
	Funcs                []string `protobuf:"bytes,5,rep,name=funcs,proto3" json:"funcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{7}
}

func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleInfo.Unmarshal(m, b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
}
func (m *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(m, src)
}
func (m *RoleInfo) XXX_Size() int {
	return xxx_messageInfo_RoleInfo.Size(m)
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *RoleInfo) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *RoleInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RoleInfo) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

func (m *RoleInfo) GetFuncs() []string {
	if m != nil {
		return m.Funcs
	}
	return nil
}

type UserListResponse struct {
	UserList             []*UserInfo `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{8}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetUserList() []*UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

type UserInfo struct {
	EmployeeId           string   `protobuf:"bytes,1,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	EmployeeName         string   `protobuf:"bytes,2,opt,name=employeeName,proto3" json:"employeeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{9}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *UserInfo) GetEmployeeName() string {
	if m != nil {
		return m.EmployeeName
	}
	return ""
}

type TransferDataRequest struct {
	SourceId             string   `protobuf:"bytes,1,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	TargetId             string   `protobuf:"bytes,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferDataRequest) Reset()         { *m = TransferDataRequest{} }
func (m *TransferDataRequest) String() string { return proto.CompactTextString(m) }
func (*TransferDataRequest) ProtoMessage()    {}
func (*TransferDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{10}
}

func (m *TransferDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferDataRequest.Unmarshal(m, b)
}
func (m *TransferDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferDataRequest.Marshal(b, m, deterministic)
}
func (m *TransferDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferDataRequest.Merge(m, src)
}
func (m *TransferDataRequest) XXX_Size() int {
	return xxx_messageInfo_TransferDataRequest.Size(m)
}
func (m *TransferDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferDataRequest proto.InternalMessageInfo

func (m *TransferDataRequest) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *TransferDataRequest) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

type TransferDataResponse struct {
	DataList             []*TransferItem `protobuf:"bytes,1,rep,name=dataList,proto3" json:"dataList,omitempty"`
	PassDataList         []string        `protobuf:"bytes,2,rep,name=passDataList,proto3" json:"passDataList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TransferDataResponse) Reset()         { *m = TransferDataResponse{} }
func (m *TransferDataResponse) String() string { return proto.CompactTextString(m) }
func (*TransferDataResponse) ProtoMessage()    {}
func (*TransferDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{11}
}

func (m *TransferDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferDataResponse.Unmarshal(m, b)
}
func (m *TransferDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferDataResponse.Marshal(b, m, deterministic)
}
func (m *TransferDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferDataResponse.Merge(m, src)
}
func (m *TransferDataResponse) XXX_Size() int {
	return xxx_messageInfo_TransferDataResponse.Size(m)
}
func (m *TransferDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferDataResponse proto.InternalMessageInfo

func (m *TransferDataResponse) GetDataList() []*TransferItem {
	if m != nil {
		return m.DataList
	}
	return nil
}

func (m *TransferDataResponse) GetPassDataList() []string {
	if m != nil {
		return m.PassDataList
	}
	return nil
}

type TransferItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Disable              bool     `protobuf:"varint,3,opt,name=disable,proto3" json:"disable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferItem) Reset()         { *m = TransferItem{} }
func (m *TransferItem) String() string { return proto.CompactTextString(m) }
func (*TransferItem) ProtoMessage()    {}
func (*TransferItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{12}
}

func (m *TransferItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferItem.Unmarshal(m, b)
}
func (m *TransferItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferItem.Marshal(b, m, deterministic)
}
func (m *TransferItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferItem.Merge(m, src)
}
func (m *TransferItem) XXX_Size() int {
	return xxx_messageInfo_TransferItem.Size(m)
}
func (m *TransferItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferItem.DiscardUnknown(m)
}

var xxx_messageInfo_TransferItem proto.InternalMessageInfo

func (m *TransferItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TransferItem) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *TransferItem) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "role.Request")
	proto.RegisterType((*Response)(nil), "role.Response")
	proto.RegisterType((*SubSysInfoRequest)(nil), "role.SubSysInfoRequest")
	proto.RegisterType((*SubSysInfoResponse)(nil), "role.SubSysInfoResponse")
	proto.RegisterType((*RoleListRequest)(nil), "role.RoleListRequest")
	proto.RegisterType((*RoleListResponse)(nil), "role.RoleListResponse")
	proto.RegisterType((*NewRoleRequest)(nil), "role.NewRoleRequest")
	proto.RegisterType((*RoleInfo)(nil), "role.RoleInfo")
	proto.RegisterType((*UserListResponse)(nil), "role.UserListResponse")
	proto.RegisterType((*UserInfo)(nil), "role.UserInfo")
	proto.RegisterType((*TransferDataRequest)(nil), "role.TransferDataRequest")
	proto.RegisterType((*TransferDataResponse)(nil), "role.TransferDataResponse")
	proto.RegisterType((*TransferItem)(nil), "role.TransferItem")
}

func init() { proto.RegisterFile("role.proto", fileDescriptor_48a3ff9f7c9032f8) }

var fileDescriptor_48a3ff9f7c9032f8 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5b, 0x6f, 0xd3, 0x4c,
	0x10, 0x6d, 0x9a, 0x4b, 0xdd, 0xe9, 0xf5, 0xdb, 0x2f, 0x14, 0x63, 0x21, 0x14, 0xed, 0x53, 0x55,
	0x44, 0x24, 0x0a, 0x0f, 0x48, 0x20, 0x44, 0x51, 0xd4, 0x2a, 0x08, 0x2a, 0xb4, 0xa5, 0x2f, 0x88,
	0x97, 0x4d, 0x3c, 0x29, 0xa6, 0xbe, 0xe1, 0xdd, 0x80, 0xf2, 0x2f, 0xf8, 0x2f, 0xfc, 0x41, 0xb4,
	0x37, 0x67, 0x9d, 0x80, 0x10, 0x6f, 0x7b, 0x66, 0xce, 0x9c, 0xcc, 0x1c, 0xcf, 0x04, 0xa0, 0x2a,
	0x52, 0x1c, 0x96, 0x55, 0x21, 0x0b, 0xd2, 0x51, 0x6f, 0x7a, 0x06, 0x5b, 0x0c, 0xbf, 0xce, 0x51,
	0x48, 0xf2, 0x00, 0x00, 0xb3, 0x32, 0x2d, 0x16, 0x88, 0xe3, 0x38, 0x6c, 0x0d, 0x5a, 0xc7, 0xdb,
	0xcc, 0x8b, 0x90, 0x23, 0xe8, 0xa9, 0x92, 0x71, 0x1c, 0x6e, 0xea, 0x9c, 0x45, 0xf4, 0x3e, 0x04,
	0x0c, 0x45, 0x59, 0xe4, 0x02, 0xc9, 0x21, 0xb4, 0x33, 0x71, 0x63, 0x8b, 0xd5, 0x93, 0x3e, 0x84,
	0xff, 0xae, 0xe6, 0x93, 0xab, 0x85, 0x18, 0xe7, 0xb3, 0xc2, 0xfd, 0xd4, 0x11, 0xf4, 0x44, 0x92,
	0x95, 0x29, 0x6a, 0x66, 0x97, 0x59, 0x44, 0xcf, 0x81, 0xf8, 0xe4, 0x3f, 0x89, 0xaa, 0x56, 0x45,
	0xcd, 0xb3, 0xed, 0x78, 0x11, 0x9a, 0xc0, 0x01, 0x2b, 0x52, 0x7c, 0x9b, 0x08, 0xe9, 0x7e, 0x92,
	0x40, 0x27, 0xe7, 0x19, 0x5a, 0x15, 0xfd, 0x26, 0x21, 0x6c, 0xf1, 0x38, 0x4b, 0xf2, 0x7a, 0x24,
	0x07, 0x15, 0xbb, 0xe4, 0x37, 0x18, 0xb6, 0x75, 0x7b, 0xfa, 0x4d, 0xfa, 0xd0, 0x4d, 0x93, 0x2c,
	0x91, 0x61, 0x47, 0x07, 0x0d, 0xa0, 0x9f, 0xe0, 0x70, 0xf9, 0x53, 0xb6, 0xe1, 0x53, 0xd8, 0xd5,
	0xde, 0xe4, 0xb3, 0x42, 0xc5, 0xc3, 0xd6, 0xa0, 0x7d, 0xbc, 0x73, 0xba, 0x3f, 0xd4, 0xee, 0x33,
	0x9b, 0x61, 0x0d, 0x8e, 0x52, 0x97, 0x85, 0xe4, 0xa9, 0xee, 0xa4, 0xcb, 0x0c, 0xa0, 0x2f, 0x60,
	0xff, 0x12, 0xbf, 0xab, 0x12, 0x37, 0xc7, 0x09, 0x04, 0xae, 0x4e, 0xcf, 0xb2, 0xae, 0x5b, 0xe7,
	0xe9, 0x8f, 0x16, 0x04, 0x2e, 0xec, 0x7d, 0xbe, 0x96, 0xff, 0xf9, 0x48, 0x64, 0x04, 0x2f, 0x95,
	0x39, 0xc6, 0x85, 0x1a, 0x93, 0x01, 0xec, 0xc4, 0x28, 0xa6, 0x55, 0x52, 0xca, 0xa4, 0xc8, 0xb5,
	0x1b, 0xdb, 0xcc, 0x0f, 0xf9, 0x16, 0x76, 0x9a, 0x16, 0xf6, 0xa1, 0x3b, 0x9b, 0xe7, 0x53, 0x11,
	0x76, 0x07, 0xed, 0xe3, 0x6d, 0x66, 0x00, 0x7d, 0x09, 0x87, 0xd7, 0x02, 0xab, 0x86, 0x5d, 0x27,
	0x10, 0xcc, 0x6d, 0xac, 0x69, 0x95, 0x62, 0x9a, 0x91, 0x5c, 0x9e, 0x5e, 0x42, 0xe0, 0xa2, 0x7f,
	0x5d, 0x58, 0x0a, 0xbb, 0x0e, 0x79, 0xd3, 0x35, 0x62, 0xf4, 0x1d, 0xfc, 0xff, 0xa1, 0xe2, 0xb9,
	0x98, 0x61, 0x35, 0xe2, 0x92, 0x3b, 0x97, 0x23, 0x08, 0x44, 0x31, 0xaf, 0xa6, 0x4b, 0xe1, 0x1a,
	0xab, 0x9c, 0xe4, 0xd5, 0x0d, 0xca, 0x7a, 0x6d, 0x6a, 0x4c, 0xbf, 0x40, 0xbf, 0x29, 0x67, 0x47,
	0x1c, 0x42, 0x10, 0x73, 0xc9, 0xbd, 0x11, 0x89, 0x19, 0xd1, 0xb1, 0xc7, 0x12, 0x33, 0x56, 0x73,
	0x54, 0xeb, 0x25, 0x17, 0x62, 0xe4, 0x6a, 0x36, 0xb5, 0x87, 0x8d, 0x18, 0x7d, 0x0f, 0xbb, 0x7e,
	0xb5, 0x3a, 0x93, 0x5b, 0x5c, 0xb8, 0x33, 0xb9, 0xc5, 0x85, 0xde, 0x58, 0x3e, 0xc1, 0xd4, 0xb6,
	0x69, 0x80, 0xfa, 0x64, 0x71, 0x22, 0xf8, 0x24, 0x35, 0xeb, 0x1d, 0x30, 0x07, 0x4f, 0x7f, 0xb6,
	0x61, 0x47, 0x75, 0x75, 0x85, 0xd5, 0xb7, 0x64, 0x8a, 0x64, 0x04, 0x7b, 0x17, 0x28, 0x97, 0x17,
	0x49, 0xee, 0x9a, 0xa6, 0xd7, 0x0e, 0x3a, 0x0a, 0xd7, 0x13, 0x66, 0x72, 0xba, 0x41, 0x5e, 0xc1,
	0xde, 0x39, 0xca, 0xe9, 0x67, 0x77, 0x26, 0xe4, 0xce, 0x72, 0x61, 0xbd, 0x0b, 0x8d, 0x8e, 0x56,
	0xc3, 0xb5, 0xc2, 0x33, 0xab, 0xe0, 0x36, 0x87, 0xec, 0x59, 0x6a, 0xb3, 0x72, 0x75, 0xb1, 0xe8,
	0x06, 0x79, 0x0c, 0x5b, 0x67, 0x71, 0xac, 0x24, 0x49, 0xdf, 0x90, 0x9a, 0xe7, 0x14, 0xb9, 0xe3,
	0x59, 0x96, 0x3c, 0x05, 0xb8, 0x2e, 0x63, 0x2e, 0xf1, 0x9f, 0xaa, 0x1e, 0x01, 0x8c, 0x30, 0x45,
	0x5b, 0xb5, 0xd2, 0xdf, 0x3a, 0xfd, 0x0d, 0x1c, 0x5c, 0xa0, 0xf4, 0x57, 0x85, 0xdc, 0x6b, 0x2e,
	0x84, 0xb7, 0x8d, 0x51, 0xf4, 0xbb, 0x94, 0xd3, 0x7a, 0x1d, 0x7c, 0xec, 0x0d, 0x9f, 0x2b, 0xc2,
	0xa4, 0xa7, 0xff, 0xd9, 0x9f, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x20, 0xd7, 0x19, 0x77, 0xe7,
	0x05, 0x00, 0x00,
}
