// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EmployeeId           string   `protobuf:"bytes,2,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Msg                  string    `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	LoginState           bool      `protobuf:"varint,2,opt,name=loginState,proto3" json:"loginState,omitempty"`
	UserInfo             *UserInfo `protobuf:"bytes,3,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	Roles                []string  `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetLoginState() bool {
	if m != nil {
		return m.LoginState
	}
	return false
}

func (m *Response) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *Response) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type DeptResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	DeptInfo             string   `protobuf:"bytes,2,opt,name=deptInfo,proto3" json:"deptInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeptResponse) Reset()         { *m = DeptResponse{} }
func (m *DeptResponse) String() string { return proto.CompactTextString(m) }
func (*DeptResponse) ProtoMessage()    {}
func (*DeptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *DeptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeptResponse.Unmarshal(m, b)
}
func (m *DeptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeptResponse.Marshal(b, m, deterministic)
}
func (m *DeptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeptResponse.Merge(m, src)
}
func (m *DeptResponse) XXX_Size() int {
	return xxx_messageInfo_DeptResponse.Size(m)
}
func (m *DeptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeptResponse proto.InternalMessageInfo

func (m *DeptResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DeptResponse) GetDeptInfo() string {
	if m != nil {
		return m.DeptInfo
	}
	return ""
}

type UserListRequest struct {
	// 是否是查询操作
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeptID string `protobuf:"bytes,2,opt,name=deptID,proto3" json:"deptID,omitempty"`
	// 排序方式 +id -id
	Sort string `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	// 第几页
	Page int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	// 每页项数
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

func (m *UserListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserListRequest) GetDeptID() string {
	if m != nil {
		return m.DeptID
	}
	return ""
}

func (m *UserListRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *UserListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type UserListResponse struct {
	UserInfoList         []*UserInfo `protobuf:"bytes,1,rep,name=userInfoList,proto3" json:"userInfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetUserInfoList() []*UserInfo {
	if m != nil {
		return m.UserInfoList
	}
	return nil
}

type UserInfo struct {
	EmployeeCode         string   `protobuf:"bytes,1,opt,name=EmployeeCode,proto3" json:"EmployeeCode,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	DepartmentId         string   `protobuf:"bytes,3,opt,name=DepartmentId,proto3" json:"DepartmentId,omitempty"`
	UserType             string   `protobuf:"bytes,4,opt,name=UserType,proto3" json:"UserType,omitempty"`
	Disable              bool     `protobuf:"varint,5,opt,name=Disable,proto3" json:"Disable,omitempty"`
	LastLoginTimestamp   int64    `protobuf:"varint,6,opt,name=LastLoginTimestamp,proto3" json:"LastLoginTimestamp,omitempty"`
	CreatedTimestamp     int64    `protobuf:"varint,7,opt,name=CreatedTimestamp,proto3" json:"CreatedTimestamp,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=Description,proto3" json:"Description,omitempty"`
	Alias                string   `protobuf:"bytes,9,opt,name=Alias,proto3" json:"Alias,omitempty"`
	CanChanged           bool     `protobuf:"varint,10,opt,name=CanChanged,proto3" json:"CanChanged,omitempty"`
	Phone                string   `protobuf:"bytes,11,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetEmployeeCode() string {
	if m != nil {
		return m.EmployeeCode
	}
	return ""
}

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *UserInfo) GetUserType() string {
	if m != nil {
		return m.UserType
	}
	return ""
}

func (m *UserInfo) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

func (m *UserInfo) GetLastLoginTimestamp() int64 {
	if m != nil {
		return m.LastLoginTimestamp
	}
	return 0
}

func (m *UserInfo) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *UserInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UserInfo) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *UserInfo) GetCanChanged() bool {
	if m != nil {
		return m.CanChanged
	}
	return false
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "user.Request")
	proto.RegisterType((*Response)(nil), "user.Response")
	proto.RegisterType((*DeptResponse)(nil), "user.DeptResponse")
	proto.RegisterType((*UserListRequest)(nil), "user.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "user.UserListResponse")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x6e, 0xde, 0xce, 0x24, 0xb4, 0xd1, 0x0a, 0xaa, 0x55, 0x0e, 0xc8, 0xf2, 0x29, 0xea, 0x21,
	0x87, 0x70, 0x84, 0x0b, 0x8d, 0xa1, 0x8a, 0x94, 0x03, 0x72, 0xcb, 0x01, 0x6e, 0xdb, 0x7a, 0x48,
	0x2d, 0xd9, 0xde, 0xc5, 0xbb, 0x05, 0x55, 0x48, 0xdc, 0xf9, 0xab, 0xfc, 0x0a, 0x34, 0xe3, 0x47,
	0x9c, 0x52, 0xb5, 0xb7, 0xf9, 0xbe, 0xf9, 0x76, 0xde, 0x36, 0xc0, 0x9d, 0xc5, 0x62, 0x69, 0x0a,
	0xed, 0xb4, 0xe8, 0x93, 0x1d, 0x7c, 0x81, 0x51, 0x84, 0xdf, 0xef, 0xd0, 0x3a, 0x21, 0xa0, 0x9f,
	0xab, 0x0c, 0x65, 0xc7, 0xef, 0x2c, 0xc6, 0x11, 0xdb, 0xe2, 0x35, 0x00, 0x66, 0x26, 0xd5, 0xf7,
	0x88, 0x9b, 0x58, 0x76, 0xd9, 0xd3, 0x62, 0xc4, 0x1c, 0x3c, 0xa3, 0xac, 0xfd, 0xa9, 0x8b, 0x58,
	0xf6, 0xd8, 0xdb, 0xe0, 0xe0, 0x37, 0x78, 0x11, 0x5a, 0xa3, 0x73, 0x8b, 0x62, 0x06, 0xbd, 0xcc,
	0xee, 0xaa, 0xd0, 0x64, 0x52, 0xe4, 0x54, 0xef, 0x92, 0xfc, 0xd2, 0x29, 0x87, 0x1c, 0xd9, 0x8b,
	0x5a, 0x8c, 0x38, 0x03, 0x8f, 0x0a, 0xdc, 0xe4, 0xdf, 0x34, 0x47, 0x9e, 0xac, 0x8e, 0x97, 0x5c,
	0xfd, 0xe7, 0x8a, 0x8d, 0x1a, 0xbf, 0x78, 0x09, 0x83, 0x42, 0xa7, 0x68, 0x65, 0xdf, 0xef, 0x2d,
	0xc6, 0x51, 0x09, 0x82, 0x77, 0x30, 0x0d, 0xd1, 0xb8, 0x27, 0x6a, 0x98, 0x83, 0x17, 0xa3, 0x71,
	0x9c, 0xa3, 0xec, 0xad, 0xc1, 0xc1, 0x2f, 0x38, 0xa1, 0x4c, 0xdb, 0xc4, 0xba, 0xa7, 0x06, 0x74,
	0x0a, 0x43, 0x7e, 0x12, 0x56, 0x01, 0x2a, 0x44, 0x5a, 0xab, 0x0b, 0x57, 0x0d, 0x85, 0x6d, 0xe2,
	0x8c, 0xda, 0xa1, 0xec, 0xfb, 0x9d, 0xc5, 0x20, 0x62, 0x9b, 0x4a, 0x4f, 0x93, 0x2c, 0x71, 0x72,
	0xc0, 0x64, 0x09, 0x82, 0x8f, 0x30, 0xdb, 0x27, 0xaf, 0xca, 0x5f, 0xc1, 0xb4, 0x6e, 0x98, 0x78,
	0xd9, 0xf1, 0x7b, 0x8f, 0x0c, 0xe5, 0x40, 0x13, 0xfc, 0xed, 0x82, 0x57, 0xbb, 0x44, 0x00, 0xd3,
	0x0f, 0xd5, 0xe6, 0xd6, 0x3a, 0xae, 0xdb, 0x38, 0xe0, 0xa8, 0x1d, 0xd6, 0xd7, 0xbb, 0xae, 0x10,
	0xbd, 0x0d, 0xd1, 0xa8, 0xc2, 0x65, 0x98, 0xbb, 0x4d, 0xbd, 0xeb, 0x03, 0x8e, 0xa6, 0x49, 0xea,
	0xab, 0x7b, 0x53, 0xb6, 0x38, 0x8e, 0x1a, 0x2c, 0x24, 0x8c, 0xc2, 0xc4, 0xaa, 0xeb, 0x14, 0xb9,
	0x51, 0x2f, 0xaa, 0xa1, 0x58, 0x82, 0xd8, 0x2a, 0xeb, 0xb6, 0xb4, 0xf9, 0xab, 0x24, 0x43, 0xeb,
	0x54, 0x66, 0xe4, 0xd0, 0xef, 0x2c, 0x7a, 0xd1, 0x23, 0x1e, 0x71, 0x06, 0xb3, 0x75, 0x81, 0xca,
	0x61, 0xbc, 0x57, 0x8f, 0x58, 0xfd, 0x1f, 0x2f, 0x7c, 0x98, 0x84, 0x68, 0x6f, 0x8a, 0xc4, 0xb8,
	0x44, 0xe7, 0xd2, 0xe3, 0xa2, 0xda, 0x14, 0x8d, 0xff, 0x7d, 0x9a, 0x28, 0x2b, 0xc7, 0xec, 0x2b,
	0x01, 0xdd, 0xe6, 0x5a, 0xe5, 0xeb, 0x5b, 0x95, 0xef, 0x30, 0x96, 0x50, 0xde, 0xe6, 0x9e, 0xa1,
	0x57, 0x9f, 0x6e, 0x75, 0x8e, 0x72, 0x52, 0xbe, 0x62, 0xb0, 0xfa, 0xd3, 0x85, 0x09, 0x4d, 0xff,
	0x12, 0x8b, 0x1f, 0xc9, 0x0d, 0x8a, 0x05, 0x0c, 0x2e, 0x0a, 0x44, 0x27, 0x5e, 0x94, 0x3b, 0xaa,
	0xce, 0x68, 0x7e, 0x5c, 0xc3, 0x72, 0xb1, 0xc1, 0x11, 0x29, 0xb9, 0xcb, 0xe7, 0x95, 0x4b, 0x98,
	0x5c, 0xa0, 0x6b, 0x56, 0xfa, 0xac, 0xfe, 0x1c, 0x4e, 0x5a, 0x7a, 0xba, 0x09, 0xf1, 0x6a, 0x7f,
	0x31, 0xad, 0xe3, 0x9e, 0x9f, 0x3e, 0xa4, 0x9b, 0x18, 0x2b, 0xce, 0x19, 0x56, 0x1f, 0xc6, 0xc3,
	0x9c, 0xa2, 0x84, 0xed, 0x2f, 0x2d, 0x38, 0x3a, 0xf7, 0xbe, 0x0e, 0x97, 0x6f, 0xc9, 0x71, 0x3d,
	0xe4, 0xbf, 0xcd, 0x9b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x57, 0x46, 0x83, 0x4a, 0x7b, 0x04,
	0x00, 0x00,
}
